version: 2
updates:
- package-ecosystem: "docker"
  directory: "/docker"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    npm_and_yarn:
      patterns:
      - "*"
  cooldown:
    default-days: 7
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    actions-deps:
      patterns:
      - "*"
  cooldown:
    default-days: 7
