name: Build and Test

on:
  push:
    branches:
    - main
    paths:
    - 'package**.json'
    - 'src/**'
  pull_request:
    paths:
    - 'package**.json'
    - 'src/**'
    - 'Dockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: 🧪 Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test

  build-container:
    name: 📦 Build Container
    needs: test
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
  deploy:
    name: 🚀 Deploy
    needs: build-container
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Step
        run: echo "Deploying"
